import type { components } from './api'

export type Me = components['schemas']['MeResource']
export type Role = components['schemas']['RoleResource']
export type PermissionItem = components['schemas']['PermissionResource']
export type Permission = components['schemas']['Permission']
export type UserListItem = components['schemas']['UserResource']
export type ChangeHistoryEntry = components['schemas']['ChangeHistoryResource']

export type LaravelPaginator<T> = {
  data: Array<T>
  links: {
    first: string | null
    last: string | null
    prev: string | null
    next: string | null
  }
  meta: {
    current_page: number
    from: number | null
    last_page: number
    links: Array<{
      url: string | null
      label: string
      active: boolean
    }>
    path: string | null
    per_page: number
    to: number | null
    total: number
  }
}

export type Paginated<T> = LaravelPaginator<T>

export type {
  AlertsRules,
  BankDetails,
  BusinessRulesDocument,
  BusinessRulesVersion,
  CalendarSettings,
  CancellationBand,
  CharterSettings,
  CommissionRules,
  ConfigChange,
  ConfigPublisher,
  ConfigValidation,
  ConfigVersion,
  ConfigVersionDetail,
  ConfigVersionSummary,
  ConfigWarning,
  ConsentVersions,
  CopySettings,
  DiscountsRules,
  DocumentsRules,
  EngineSettingsDocument,
  EngineSettingsValidation,
  EngineSettingsVersion,
  ExtrasCatalogue,
  ExtrasCatalogueItem,
  ExtrasDocument,
  ExtrasVersion,
  FeesSettings,
  GuestsSettings,
  HoldsRules,
  LegalEntity,
  LocaleSettings,
  ManifestsRules,
  NoRate,
  PaymentsRules,
  PngFees,
  PriceCheckRow,
  Quote,
  QuoteLine,
  RateRules,
  RateTerms,
  RateYear,
  RatesDocument,
  RatesVersion,
  RetentionRules,
  RuleGroup,
  RuleRegistryCounts,
  RuleRegistryRow,
  RuleStatus,
  RuleWhere,
  SlaRules,
} from './config'

export type {
  AllowedTransition,
  Booking,
  BookingAuditRow,
  BookingFormOptions,
  BookingListItem,
  BookingOwner,
  BookingRequestSummary,
  BookingQuote,
  BookingQuoteRequest,
  BookingSegment,
  BookingStatus,
  BookingType,
  ChannelOfOrigin,
  Contact,
  ContactSearchResult,
  CreateReservationRequest,
  CreateReservationResponse,
  Group,
  GroupSummary,
  HoldListItem,
  HoldListRules,
  MainChannel,
  MovePreview,
  PreferredChannel,
  PriceLine,
  RequestQueueItem,
  RequestQueueRules,
  WaitlistEntry,
} from './bookings'

export type {
  BookingConsent,
  Consent,
  ConsentDocument,
  ConsentSource,
  ContactInRow,
  Country,
  Guest,
  GuestIssue,
  GuestIssueSeverity,
  GuestListSummary,
  DepartureGuestExperience,
  GuestPreferences,
  GuestPreferencesInput,
  GuestResponse,
  GuestResponseInput,
  MaskedNote,
  NationalitiesSummary,
  NationalityRow,
  NpsView,
  PngCategory,
  PreferenceQuestion,
} from './guests'

export type {
  BookingExtra,
  ExtrasListSummary,
  ExtrasVersionDetail,
} from './extras'

export type {
  ClientDocumentFilters,
  ClientDocumentRow,
  Delivery,
  DeliveryKind,
  DeliveryStatus,
  DocumentKind,
  DocumentPlanKind,
  DocumentPlanRow,
  DocumentStatus,
  IssuedDocument,
  ManifestIssued,
  ManifestKind,
  ManifestRow,
  ManifestVersion,
} from './documents'

export type {
  Alert,
  AlertCounts,
  AlertKind,
  AlertKindRow,
  AlertSeverity,
} from './alerts'

export type {
  CharterEnquiry,
  CharterEnquiryStatus,
  CompleteLink,
  Offer,
  OfferChannel,
  OfferStatus,
  OfferType,
} from './offers'

export type {
  AttributionInput,
  AttributionTouch,
  CheckoutCreated,
  CheckoutExtended,
  CheckoutPath,
  CheckoutStatus,
  CheckoutSubmitted,
  CompleteBooking,
  CompleteDeclaration,
  CompleteGuest,
  CompleteReservation,
  EngineCabin,
  EngineCharterEnquiry,
  EngineCountry,
  EngineDeparture,
  EngineEventName,
  EngineEventParams,
  EngineEventsAccepted,
  EngineEventsInput,
  EngineFeed,
  EngineItinerary,
  EngineOffer,
  EngineOfferType,
  EngineQuote,
  EngineRates,
  EngineSettings,
  EngineWaitlist,
  PriceChangedError,
  PromoCheck,
  QuestionnaireAnswersInput,
  QuestionnaireView,
  SurveyInput,
  SurveyView,
} from './engine'

export type {
  ActivityEvent,
  ActivityKpis,
  Contact as CrmContact,
  ContactBooking,
  ContactDuplicate,
  ContactFilters,
  ContactMerge,
  ContactMergeResult,
  ContactProfile,
  ContactType,
  ContactUnmergeResult,
  EventCatalogueRow,
  Lifecycle,
  OwnershipRow,
  RetrySyncFailure,
  ScheduledJobCatalogueRow,
  ScheduledJobRun,
  Segment,
  SyncFailure,
  SyncIdentityRow,
  SyncKpis,
  ActivityInput,
  AssignDealInput,
  AttributionModelRow,
  BindDealInput,
  Campaign,
  CampaignBooking,
  CampaignInput,
  CampaignMeasures,
  CampaignOffer,
  CampaignUpdate,
  CompleteTaskInput,
  ConsentPurpose,
  ConsentRegisterRow,
  ContactActivity,
  ContactConsentEntry,
  ContactConsentState,
  CrmTask,
  DataMapRow,
  DealDetail,
  DealInput,
  DealStage,
  DealType,
  DeliveryKpis,
  DeliveryRow,
  MoveDealInput,
  PipelineColumn,
  PipelineDeal,
  PipelineKpis,
  RecordConsentInput,
  StageMapRow,
  TaskInput,
  TaskKind,
  TaskKpis,
  TaskUpdate,
  TimelineItem,
} from './crm'

export type {
  CloseSubjectRequestInput,
  EraseSubjectRequestInput,
  SubjectRequest,
  SubjectRequestChannel,
  SubjectRequestInput,
  SubjectRequestStatus,
  SubjectRequestType,
} from './privacy'

export type {
  AgenciesKpis,
  Agency,
  AgencyListItem,
  AgencyStatus,
  AgencyUser,
  AgencyUserInput,
  AgencyUserUpdate,
  CancellationBandLabel,
  CommissionPayout,
  CommissionPayoutInput,
  CommissionRow,
  CommissionStatus,
  Payment,
  PaymentKind,
  PaymentLink,
  PaymentListItem,
  PaymentMethod,
  PaymentOption,
  PaymentOptions,
  PaymentStatus,
  PaymentsKpis,
  PortalPreview,
  ReconciliationReport,
  ReconciliationRow,
  RefundRequest,
  RefundsRules,
  RefundStatus,
} from './payments'

export type {
  Availability,
  AvailabilityCounts,
  BlockClaim,
  BlockReason,
  Cabin,
  CabinAvailability,
  CabinCategory,
  CabinState,
  CabinUnavailableError,
  CabinUnavailableItem,
  CalendarCell,
  CalendarDeparture,
  CalendarGrid,
  CalendarRow,
  ClaimHolder,
  ClaimKind,
  ClaimSummary,
  Departure,
  DepartureKpis,
  DepartureLayout,
  DepartureListItem,
  DepartureLocks,
  DepartureMutationResponse,
  DepartureStatus,
  EngineLabel,
  EngineLabelCode,
  EngineLabelTone,
  GenerateSeasonResult,
  HoldType,
  InternalBlock,
  Itinerary,
  ItineraryCompleteness,
  ItineraryDefaults,
  ItineraryGradient,
  ItineraryListItem,
  ItineraryPair,
  ItineraryStatus,
  Yacht,
} from './inventory'
